(lang dune 3.24)

(name fplib)

(generate_opam_files true)

(source
 (github joaogabrielfer/fplib))

(authors "João Gabriel Fernandes <joaogabrielfer28@gmail.com>")

(maintainers "João Gabriel Fernandes <joaogabrielfer28@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name fplib)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
